language: cpp
dist: trusty
sudo: required
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmysqlclient-dev
      - doxygen
      - g++-4.9

script:
  - if [[ "${TRAVIS_EVENT_TYPE}" == "cron" && "${CXX}" == "g++"  ]];
    then ./.travis-ci.d/coverity_scan.sh;
    else ./.travis-ci.d/compile_and_test.sh;
    fi

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - ./.travis-ci.d/install_dependencies.sh

after_success:
  - ./.travis-ci.d/deploy-doxygen.sh

compiler:
  - gcc
  - clang

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always