language: cpp
dist: trusty
sudo: required

env:
  - ROOT_VERSION=6.10.08

os: linux
compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8.3 # default, osx 10.12
    - os: osx
      compiler: clang
      osx_image: xcode9.3 # osx 10.13

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libmysqlclient-dev
      - doxygen
      - g++-4.9

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX}" == "g++"  ]];
    then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90;
    fi
  - ./.travis-ci.d/compile_and_test.sh

before_install:
  - ./.travis-ci.d/install_dependencies.sh
  - if [[ "${TRAVIS_OS_NAME}" == "osx"  ]];
    then brew install mysql;
    fi

after_success:
  - ./.travis-ci.d/deploy-doxygen.sh

# Don't send e-mail notifications
notifications:
  email:
    on_success: never
    on_failure: always